site_name: Ballerina Blog
repo_url: https://github.com/ballerina-platform/blog
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
copyright: 2018 WSO2, Inc.
pages:
- Home: 'index.md'
- Introduction to Ballerina 0.970 release : 'posts/introduction-to-ballerina-0.970.md'
- Ballerina - A cloud native programming language for integration : 'posts/ballerina-a-cloud-native-programming-language.md'
- Ballerina Meets Hasura : 'posts/ballerina-meets-hasura.md'
- Improvements and New Features in Ballerina 0.980.0 Release : 'posts/improvements-and-new-features-in-ballerina-0.980.0-release.md'
- Introduction to New Features and Changes Introduced with Ballerina 0.982.0 : 'posts/introduction-to-new-features-and-changes-introduced-with-ballerina-0.982.0.md'


theme: null
theme_dir: ballerina.io-blog-theme
base_common_resouce_url : 'https://ballerina.io'
markdown_extensions:
 - meta
